# Generated by Django 5.2.1 on 2025-05-26 12:23

import cookbook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='recipes/images/default.jpg', null=True, upload_to=cookbook.models.recipe_image_path),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('appetizer', 'Appetizer'), ('snack', 'Snack'), ('dessert', 'Dessert'), ('drink', 'Drink'), ('side', 'Side Dish')], default='lunch', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='dietary_restrictions',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='cookbook.dietaryrestriction'),
        ),
    ]
